version: "3"

services:
  jetson-service:
    image: detection-stream:jetson-latest
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/argus_socket:/tmp/argus_socket"
      - "${PWD}/weights:/root/app/weights"
    tty: true
    stdin_open: true
    env_file:
      - ${PWD}/jetson.env

  linux-service:
    image: detection-stream:bullseye-latest
    network_mode: "host"