version: "3"

services:
  jetson-service:
    image: rcland12/detection-stream:jetson-latest
    network_mode: "host"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/argus_socket:/tmp/argus_socket"
      - "${PWD}/weights:/root/app/weights"
    tty: true
    stdin_open: true
    env_file:
      - ${PWD}/.env

  linux-service:
    image: rcland12/detection-stream:bullseye-latest
    network_mode: "host"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "${PWD}/weights:/root/app/weights"
    tty: true
    stdin_open: true
    env_file:
      - ${PWD}/.env
  
  nginx-stream:
    image: rcland12/detection-stream:nginx-latest
    network_mode: "host"
    volumes:
      - "${PWD}/nginx/nginx-stream/nginx.conf:/etc/nginx/nginx.conf"
  
  nginx-web:
    image: rcland12/detection-stream:nginx-latest
    network_mode: "host"
    volumes:
      - "${PWD}/nginx/nginx-web/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/nginx/nginx-web/hollystream.conf:/etc/nginx/conf.d/hollystream.conf"
      - "${PWD}/nginx/stream:/var/www/html/stream"