version: "3"

services:
  linux-stream:
    image: rcland12/detection-stream:bullseye-latest
    build:
      context: ./
      dockerfile: Dockerfile.linux
    network_mode: "host"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "${PWD}/weights:/root/app/weights"
    tty: true
    stdin_open: true
    env_file:
      - ${PWD}/.env
  
  nginx-stream:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    network_mode: "host"
    volumes:
      - "${PWD}/nginx/nginx-stream/nginx.conf:/etc/nginx/nginx.conf"
  
  nginx-web:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    network_mode: "host"
    volumes:
      - "${PWD}/nginx/nginx-web/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/nginx/stream:/var/www/html/stream"