version: "3"

services:
  triton:
    image: rcland12/detection-stream:triton-1.0
    build:
      context: ./triton
    shm_size: '1gb'
    volumes:
      - "${PWD}/triton:/root/app/triton"
    network_mode: "host"
    env_file:
      - ${PWD}/.env
    healthcheck:
      test: ["CMD", "curl", "-i", "-X", "GET", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3

  jetson-stream:
    image: rcland12/detection-stream:jetson-1.0
    build:
      context: ./app
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/argus_socket:/tmp/argus_socket"
      - "${PWD}/triton:/root/app/triton"
    network_mode: "host"
    env_file:
      - ${PWD}/.env
    restart: unless-stopped

  nginx-stream:
    image: rcland12/detection-stream:nginx-1.0
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - "${PWD}/nginx/nginx-stream/nginx.conf:/etc/nginx/nginx.conf"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx-web:
    image: rcland12/detection-stream:nginx-1.0
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - "${PWD}/nginx/nginx-web/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/nginx/stream:/var/www/html/stream"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3