name: Build and Push Image to Docker Hub

on:
  push:
    branches: [ jetson ]

env:
  DOCKERHUB_USERNAME: rcland12
  DOCKERHUB_REPO: detection-stream
  NGINX_TAG: nginx-latest

jobs:
  nginx-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && touch .env

    - name: Building images
      run: docker compose build --push nginx-stream
